### ISSUE TITLE
New Design for Vue 3 JSX

### ISSUE THREAD

**Issue by Amour1688** [vuejs/jsx-next#10]
Implementation Detail and new Design to discuss

* vModel
* slot
* directives
* modifiers
* ...

**Comment by tangjinzhou** [comment]
<com vModel_xxx></com>
<slot></slot> <slot name="xxx"></slot>
<template vSlot_xxx></template>

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/jsx/issues/141

**Comment by wonderful-panda** [comment]
## About '.sync' modifier

In vue-next, we should use `v-model` instead of `.sync` modifier.

```tsx
<MyComp v-model={[value, "foo"]} />
```

But I think this is not suitable for TSX in some points.

1. TypeScript can't check type of value is assignable to foo or not.

2. When foo is defined as required, TS2322 (`Property 'foo' is missing in ...`) will occur

I guess it is not impossible to solve them by changing type definitions, but it will makes type definitions too complex.

Simple solution is giving up v-model.
```tsx
<MyComp foo={value} on={{ "update:foo": v => value = v }} />
```

Is there any other (more smart) solutions ?

**Comment by Amour1688** [comment]
```jsx
<MyComp foo={value} on={{ "update:foo": v => value = v }} />
```

Will you change type definitions when giving up v-model like above.

```ts
interface Props {
  foo?: string;
  on?: {
    'update:foo': (val: string) => void;
  }
}
```

Or

```tsx
interface Props {
  vModel?: [string, 'foo']
}
```
